### ISSUE TITLE
Only getting 8 out of 16 bytes encrypted

### ISSUE THREAD

**Issue by SEKCobra** [Octoate/ArduinoDES#7]
Hey there,

I am using the following line:
des.encrypt(writeData, encryptData, encryptionKey);
writeData is a 16 byte uint8_t array, so is encryptData. I've varied encryptionKey between 8 and 16 entry byte arrays, but the result in writeData is always the first 8 bytes changed (encrypted, presumably), but the later 8 are still the initial value. Since the code for this library is way above my level, I was hoping you could help me with this.

Cheers

**Comment by Octoate** [comment]
Hi SEKCobra,
thanks for using this library. DES uses a block size of 64bits (8 bytes), which means that it will only encrypt 8 bytes in one step. You have to use a pointer to the start of the byte array and move it in 8 byte blocks over the input array (note: this will modify your input array, of course). Here is an example for this:

```
byte out[MESSAGE_LENGTH];
byte in[] = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10 };

for (int i = 0; i < MESSAGE_LENGTH; i += 8)
{
	des.encrypt((byte*)out + i, (byte*)in + i, key);
}
```
Please also have a look at the DesedeCBC examples, because they will also show an example for your use case and will also use 3DES and CBC, which is more secure instead of simple DES encryption.
